import { useEffect, useState } from 'react';
import { toast } from 'react-toastify';
import axios from '../services/axiosConfig';
const repairLabels = { ChoXuLy: 'Chờ xử lý', DangXuLy: 'Đang xử lý', HoanThanh: 'Hoàn thành', TuChoi: 'Từ chối' };
const paymentLabels = { ChoThanhToan: 'Chờ thanh toán', DaThanhToan: 'Đã thanh toán', QuaHan: 'Quá hạn', TuChoi: 'Từ chối' };
const OwnerOperationsPage = () => {
 const [repairs,setRepairs]=useState([]),[payments,setPayments]=useState([]),[contracts,setContracts]=useState([]),[form,setForm]=useState({contractId:'',period:'',amount:'',dueDate:'',note:''});
 const load=async()=>{try{const [r,p,c]=await Promise.all([axios.get('/repairs'),axios.get('/payments'),axios.get('/contracts')]);setRepairs(r.data);setPayments(p.data);setContracts(c.data.filter(x=>x.TrangThai==='HieuLuc'));}catch{toast.error('Không thể tải dữ liệu quản lý.');}};
 useEffect(()=>{load();},[]);
 const updateRepair=async(id,status)=>{try{await axios.patch(`/repairs/${id}/status`,{status});toast.success('Đã cập nhật.');load();}catch{toast.error('Cập nhật thất bại.');}};
 const markPaid=async id=>{try{await axios.patch(`/payments/${id}/paid`,{});toast.success('Đã xác nhận thanh toán.');load();}catch{toast.error('Cập nhật thất bại.');}};
 const createPayment=async e=>{e.preventDefault();try{await axios.post('/payments',form);toast.success('Đã tạo hóa đơn.');setForm({contractId:'',period:'',amount:'',dueDate:'',note:''});load();}catch(e){toast.error(e.response?.data?.message||'Tạo hóa đơn thất bại.');}};
 return <div className="container py-4"><h1 className="mb-4">Vận hành nhà cho thuê</h1><div className="card mb-4"><div className="card-header bg-primary text-white"><h5 className="mb-0">Yêu cầu sửa chữa</h5></div><div className="card-body table-responsive"><table className="table"><thead><tr><th>Người thuê</th><th>Căn hộ</th><th>Sự cố</th><th>Mô tả</th><th>Trạng thái</th></tr></thead><tbody>{repairs.map(x=><tr key={x.MaYeuCau}><td>{x.HoTen}</td><td>{x.TenCanHo||'--'}</td><td>{x.LoaiSuCo}</td><td>{x.MoTa}</td><td><select className="form-select form-select-sm" value={x.TrangThai} onChange={e=>updateRepair(x.MaYeuCau,e.target.value)}>{Object.entries(repairLabels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></td></tr>)}</tbody></table></div></div><div className="row g-4"><div className="col-lg-4"><div className="card"><div className="card-header bg-success text-white">Tạo hóa đơn</div><div className="card-body"><form onSubmit={createPayment}><select className="form-select mb-3" value={form.contractId} onChange={e=>{const c=contracts.find(x=>String(x.MaHopDong)===e.target.value);setForm({...form,contractId:e.target.value,amount:c?.GiaThue||form.amount});}} required><option value="">Chọn hợp đồng</option>{contracts.map(x=><option key={x.MaHopDong} value={x.MaHopDong}>{x.TenCanHo} — {x.HoTen}</option>)}</select><input className="form-control mb-3" type="date" value={form.period} onChange={e=>setForm({...form,period:e.target.value})} required/><input className="form-control mb-3" type="number" placeholder="Số tiền" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})} required/><input className="form-control mb-3" type="date" value={form.dueDate} onChange={e=>setForm({...form,dueDate:e.target.value})} required/><button className="btn btn-success w-100">Tạo hóa đơn</button></form></div></div></div><div className="col-lg-8"><div className="card"><div className="card-header">Danh sách hóa đơn</div><div className="card-body table-responsive"><table className="table"><thead><tr><th>Căn hộ</th><th>Kỳ</th><th>Số tiền</th><th>Trạng thái</th><th></th></tr></thead><tbody>{payments.map(x=><tr key={x.MaHoaDon}><td>{x.TenCanHo}</td><td>{new Date(x.KyThanhToan).toLocaleDateString('vi-VN')}</td><td>{Number(x.SoTien).toLocaleString('vi-VN')} đ</td><td>{paymentLabels[x.TrangThai]}</td><td>{x.TrangThai!=='DaThanhToan'&&<button className="btn btn-sm btn-outline-success" onClick={()=>markPaid(x.MaHoaDon)}>Đã thu</button>}</td></tr>)}</tbody></table></div></div></div></div></div>;
};
export default OwnerOperationsPage;
